### ISSUE TITLE
请问开放平台的借口能用么？

### ISSUE THREAD

**Issue by wizarddewhite** [yaotian/gowechat#1]
我在文档里看到开放平台这一块是空的，不确定是没有做还是文档没有写？

**Comment by yaotian** [comment]
开放平台还未实现。但一般是用来登陆。
关于登陆，微信公众平台如果是服务号的话，有更好的解决方案。OAuth+带参数二维码来实现扫码登陆。

**Comment by ezewu** [comment]
OAuth+带参数二维码来实现扫码登陆，这个有实现吗
